version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5425:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 1@1.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"

# to connect, in pgadmin the ip is host.docker.internal instead of localhost, and the port is 5425
